apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bookstores.calico.com
spec:
  group: calico.com
  names:
    kind: Bookstore
    listKind: BookstoreList
    plural: bookstores
    singular: bookstore
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            kind:
              type: string
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            metadata:
              type: object
            spec:
              type: object
              description: 'Desired state of the CRD'
              properties:
                deploymentImageName:
                  type: string
                deploymentImageTag:
                  type: string
                deploymentName:
                  type: string
                replicas:
                  format: int32
                  type: integer
                serviceName:
                  type: string
                containerPort:
                  format: int32
                  type: integer
                nodePort:
                  format: int32
                  type: integer
                targetPort:
                  format: int32
                  type: integer
              required:
                - deploymentImageName
                - deploymentImageTag
                - deploymentName
                - replicas
                - serviceName
                - containerPort
                - nodePort
                - targetPort
            status:
              type: object
              description: 'Observed state of the CRD'
              properties:
                availableReplicas:
                  format: int32
                  type: integer
          required:
            - spec


